@startuml
Participant LwM2MInboundTopic as topic
Participant "Device Manager" as dm
Participant "Redis" as redis

topic <- dm: poll messages
loop each messages
dm -> redis : set cdm:deviceManager:inbound-message:${uuid} Lwm2mServerToCDMMessage 3600

end
@enduml